"""The Cursor plugin uses only documented manifest keys and ships its routing rule.

The key sets and the rules location come from `registry/hosts.json`
(`cursor.plugin_format`), which cites Cursor's plugin reference. Installing the
plugin from a marketplace used to deliver the skills without the routing rule,
because only `scripts/install-cursor.sh` copied it.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tooling"))
import generate_adapters as adapters  # noqa: E402
from compatibility import safe_load_unique  # noqa: E402

CURSOR = json.loads((ROOT / "registry" / "hosts.json").read_text(encoding="utf-8"))["hosts"]["cursor"]
FORMAT = CURSOR["plugin_format"]
REGISTRY = json.loads((ROOT / "registry" / "skills.json").read_text(encoding="utf-8"))["skills"]


def read_json(relative: str) -> dict:
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


def test_plugin_format_cites_the_cursor_reference() -> None:
    assert FORMAT["source"] == "https://cursor.com/docs/reference/plugins"
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", FORMAT["verified_at"])
    assert FORMAT["manifest"] == ".cursor-plugin/plugin.json"


def test_cursor_manifest_uses_only_documented_keys() -> None:
    manifest = read_json(FORMAT["manifest"])
    assert set(manifest) <= set(FORMAT["manifest_keys"]), sorted(set(manifest) - set(FORMAT["manifest_keys"]))
    assert set(manifest.get("author", {})) <= set(FORMAT["author_keys"])
    assert "displayName" not in manifest


def test_cursor_marketplace_uses_only_documented_keys() -> None:
    market = read_json(".cursor-plugin/marketplace.json")
    assert set(market) <= set(FORMAT["marketplace_keys"])


def test_cursor_manifest_is_the_claude_manifest_restricted_to_cursor_keys() -> None:
    claude = read_json(".claude-plugin/plugin.json")
    assert read_json(FORMAT["manifest"]) == adapters.cursor_manifest_from(claude, FORMAT)


def test_projection_drops_undocumented_keys_and_author_fields() -> None:
    claude = {"name": "p", "displayName": "P", "version": "1.0.0",
              "author": {"name": "A", "url": "https://example.com"}, "keywords": ["x"]}
    assert adapters.cursor_manifest_from(claude, FORMAT) == {
        "name": "p", "version": "1.0.0", "author": {"name": "A"}, "keywords": ["x"]}


def plugin_rule() -> Path:
    return ROOT / CURSOR["plugin_rule"]


def test_plugin_rule_sits_where_cursor_discovers_rules() -> None:
    manifest = read_json(FORMAT["manifest"])
    rule = plugin_rule()
    assert "rules" not in manifest, "an explicit rules key would replace folder discovery"
    assert rule.parent == ROOT / FORMAT["rules_dir"]
    assert rule.suffix in FORMAT["rule_extensions"]
    assert rule.is_file()


def test_plugin_rule_frontmatter_is_cursor_rule_frontmatter() -> None:
    text = plugin_rule().read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---\n", text, re.S)
    assert match
    front = safe_load_unique(match.group(1))
    assert set(front) <= set(FORMAT["rule_frontmatter_keys"])
    assert isinstance(front["description"], str) and front["description"].strip()
    assert front["alwaysApply"] is True


def test_plugin_rule_is_generated_and_routes_every_registry_skill() -> None:
    text = plugin_rule().read_text(encoding="utf-8")
    assert "generated by tooling/generate_adapters.py" in text
    ids = re.findall(r"^\| .+ \| `([a-z0-9-]+)` \|$", text, flags=re.MULTILINE)
    assert ids == [s["id"] for s in REGISTRY]
    assert "docs/" not in text, "the plugin ships no docs/ directory, so the rule must not point there"


def test_generator_owns_the_plugin_rule_and_the_cursor_manifest() -> None:
    artifacts = adapters.host_artifacts(REGISTRY)
    assert artifacts[plugin_rule()] == plugin_rule().read_text(encoding="utf-8")
    assert artifacts[ROOT / FORMAT["manifest"]] == (ROOT / FORMAT["manifest"]).read_text(encoding="utf-8")


def test_plugin_rule_stays_compact() -> None:
    """Always applied in every project once the plugin is installed: the compact table, not the catalog."""
    assert len(plugin_rule().read_bytes()) < 4500
