"""Repo-to-roadmap deterministic kernel package."""
from __future__ import annotations

from .cli import main
from .constants import (
    CAPABILITY_STATES,
    CLAIM_LANES,
    CLAIM_TYPES,
    COVERAGE_FACTORS,
    CURRENT_ADMISSIBLE,
    DIRECTIONS,
    DIRECTNESS,
    EFFORT_FACTORS,
    EFFORT_ORDER,
    FRESHNESS,
    GATE_STATUSES,
    GATE_TYPES,
    ITEM_KINDS,
    KERNEL_VERSION,
    LANE_MULTIPLIERS,
    LANE_ORDER,
    MATERIALITIES,
    MAX_JSON_BYTES,
    SCHEMA_VERSION,
    SCOPE_MATCH,
    SOURCE_BASE,
    TARGET_APPLICABILITY,
    TARGET_PROFILES,
    VALID_LANES,
    VERIFICATION_SOURCES,
)
from .delta import (
    assessment_contract_sha256,
    delta_report,
    snapshot_core,
    snapshot_report,
)
from .evidence import (
    absence_protocol_complete,
    combine_independent,
    evidence_report,
    evidence_row_strength,
)
from .graph import graph_report
from .inventory import coverage_report, file_coverage_report
from .prioritization import priority_inputs, priority_report, sensitivity_report
from .util import (
    by_id,
    changed_ids,
    clamp,
    default_claim_type,
    freshness_value,
    normalized,
    normalized_lower,
    normalized_upper,
    parse_json_arg,
    require_choice,
    require_probability_like,
    require_score,
    stable_json,
)
from .validation import validate_acceptance, validate_roadmap, validate_target_contract

__all__ = [
    "SCHEMA_VERSION",
    "KERNEL_VERSION",
    "MAX_JSON_BYTES",
    "SOURCE_BASE",
    "LANE_MULTIPLIERS",
    "DIRECTNESS",
    "FRESHNESS",
    "CURRENT_ADMISSIBLE",
    "SCOPE_MATCH",
    "DIRECTIONS",
    "CLAIM_LANES",
    "CLAIM_TYPES",
    "MATERIALITIES",
    "VERIFICATION_SOURCES",
    "COVERAGE_FACTORS",
    "EFFORT_FACTORS",
    "EFFORT_ORDER",
    "VALID_LANES",
    "LANE_ORDER",
    "ITEM_KINDS",
    "GATE_TYPES",
    "GATE_STATUSES",
    "CAPABILITY_STATES",
    "TARGET_PROFILES",
    "TARGET_APPLICABILITY",
    "clamp",
    "require_score",
    "require_probability_like",
    "normalized",
    "normalized_lower",
    "normalized_upper",
    "require_choice",
    "default_claim_type",
    "freshness_value",
    "evidence_row_strength",
    "combine_independent",
    "absence_protocol_complete",
    "evidence_report",
    "priority_inputs",
    "priority_report",
    "sensitivity_report",
    "graph_report",
    "coverage_report",
    "stable_json",
    "snapshot_core",
    "snapshot_report",
    "assessment_contract_sha256",
    "file_coverage_report",
    "by_id",
    "changed_ids",
    "delta_report",
    "validate_target_contract",
    "validate_acceptance",
    "validate_roadmap",
    "parse_json_arg",
    "main",
]
