#!/usr/bin/env bash
# Auto-discovers skills from skills/*/SKILL.md in the canonical public repo.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/skills.sh
source "$ROOT/scripts/lib/skills.sh"

TARGET="${CURSOR_SKILLS_DIR:-$HOME/.cursor/skills}"
mkdir -p "$TARGET"
count=0
while IFS= read -r name; do
  [[ -z "$name" ]] && continue
  src="$ROOT/skills/$name"
  dest="$TARGET/$name"
  if [[ ! -d "$src" ]]; then
    echo "FAIL: missing skill directory $src" >&2
    exit 1
  fi
  if [[ -L "$dest" ]]; then
    rm "$dest"
  elif [[ -e "$dest" ]]; then
    echo "FAIL: $dest exists and is not a symlink — move it aside first" >&2
    exit 1
  fi
  ln -s "$src" "$dest"
  echo "linked $name -> $src"
  count=$((count + 1))
done < <(list_skills)

RULE_SRC="$ROOT/docs/generated-cursor-routing.mdc"
if [[ ! -f "$RULE_SRC" ]]; then
  RULE_SRC="$ROOT/extras/cursor-routing.mdc"
fi
RULE_DEST="${CURSOR_RULES_DIR:-$HOME/.cursor/rules}/cometweb-agent-skills.mdc"
if [[ -f "$RULE_SRC" ]]; then
  mkdir -p "$(dirname "$RULE_DEST")"
  if [[ -L "$RULE_DEST" ]]; then
    rm -- "$RULE_DEST"
  fi
  if [[ ! -e "$RULE_DEST" ]]; then
    ln -s -- "$RULE_SRC" "$RULE_DEST"
    echo "linked routing rule -> $RULE_DEST"
  elif grep -q 'generated by tooling/generate_adapters.py' "$RULE_DEST" 2>/dev/null; then
    tmp="${RULE_DEST}.tmp.$$"
    cp -- "$RULE_SRC" "$tmp"
    mv -- "$tmp" "$RULE_DEST"
    echo "updated generated routing rule -> $RULE_DEST"
  else
    echo "skip routing rule: $RULE_DEST already exists"
  fi
fi

echo "OK: $count Cursor skills installed in $TARGET"
