#!/usr/bin/env bash
# shellcheck source-path=SCRIPTDIR
# Link canonical CometWeb skills into Cursor's skills directory, plus the routing rule.
# Auto-discovers skills/*/SKILL.md; run with --help for --dry-run and --uninstall.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/skills.sh
source "$ROOT/scripts/lib/skills.sh"
# shellcheck source=lib/install.sh
source "$ROOT/scripts/lib/install.sh"

RULE_SRC="$ROOT/docs/generated-cursor-routing.mdc"
if [[ ! -f "$RULE_SRC" ]]; then
  RULE_SRC="$ROOT/extras/cursor-routing.mdc"
fi
RULES_DIR="${CURSOR_RULES_DIR:-$HOME/.cursor/rules}"
RULE_DEST="$RULES_DIR/cometweb-agent-skills.mdc"
RULE_MARKER='generated by tooling/generate_adapters.py'

# Same path-escape gate as skill targets (shared helper; no .. climb-out).
# Runs before any skill is linked so a foreign rule link fails the whole install.
host_preflight() {
  resolved_install_path "$RULES_DIR" >/dev/null
  if [[ -f "$RULE_SRC" && -L "$RULE_DEST" ]]; then
    preflight_existing_path "$RULE_DEST" "$RULE_SRC"
  fi
}

host_apply() {
  local tmp
  [[ -f "$RULE_SRC" ]] || return 0
  if [[ "$INSTALL_DRY_RUN" != "1" ]]; then
    mkdir -p "$RULES_DIR"
  fi
  if [[ -L "$RULE_DEST" ]]; then
    if [[ "$(readlink "$RULE_DEST")" == "$RULE_SRC" ]]; then
      echo "routing rule already linked -> $RULE_DEST"
      return 0
    fi
    backup_existing_path "$RULE_DEST" "cursor-routing.mdc"
  elif [[ -e "$RULE_DEST" ]]; then
    if grep -q "$RULE_MARKER" "$RULE_DEST" 2>/dev/null; then
      if [[ "$INSTALL_DRY_RUN" != "1" ]]; then
        tmp="${RULE_DEST}.tmp.$$"
        cp -- "$RULE_SRC" "$tmp"
        mv -- "$tmp" "$RULE_DEST"
      fi
      echo "$(plan_verb update updated) generated routing rule -> $RULE_DEST"
    else
      echo "skip routing rule: $RULE_DEST already exists"
    fi
    return 0
  fi
  if [[ "$INSTALL_DRY_RUN" != "1" ]]; then
    ln -s -- "$RULE_SRC" "$RULE_DEST"
  fi
  echo "$(plan_verb link linked) routing rule -> $RULE_DEST"
}

# Removes the rule only when this installer owns it: a link to this checkout's
# rule, or a generated copy the installer would overwrite anyway.
host_uninstall() {
  local candidate
  resolved_install_path "$RULES_DIR" >/dev/null
  if [[ -L "$RULE_DEST" ]]; then
    for candidate in "$ROOT/docs/generated-cursor-routing.mdc" "$ROOT/extras/cursor-routing.mdc"; do
      if [[ "$(readlink "$RULE_DEST")" == "$candidate" ]]; then
        [[ "$INSTALL_DRY_RUN" == "1" ]] || rm -- "$RULE_DEST"
        echo "$(plan_verb unlink unlinked) routing rule $RULE_DEST"
        return 0
      fi
    done
    echo "skip routing rule: $RULE_DEST is not a link to this checkout"
  elif [[ -f "$RULE_DEST" ]]; then
    if grep -q "$RULE_MARKER" "$RULE_DEST" 2>/dev/null; then
      [[ "$INSTALL_DRY_RUN" == "1" ]] || rm -- "$RULE_DEST"
      echo "$(plan_verb remove removed) generated routing rule $RULE_DEST"
    else
      echo "skip routing rule: $RULE_DEST was not written by this installer"
    fi
  fi
}

run_host_installer "Cursor" "${CURSOR_SKILLS_DIR:-$HOME/.cursor/skills}" "$@"
