#!/usr/bin/env bash
# Auto-discovers skills from skills/*/SKILL.md in the canonical public repo.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/skills.sh
source "$ROOT/scripts/lib/skills.sh"
# shellcheck source=lib/install.sh
source "$ROOT/scripts/lib/install.sh"

TARGET="${CURSOR_SKILLS_DIR:-$HOME/.cursor/skills}"
skill_names="$(list_skills)"
[[ -n "$skill_names" ]] || { echo "FAIL: no skill packages found" >&2; exit 1; }
prepare_install_target "$TARGET" "$ROOT/skills"
preflight_install_conflicts "$TARGET" "$ROOT/skills" "$skill_names"
RULE_SRC="$ROOT/docs/generated-cursor-routing.mdc"
if [[ ! -f "$RULE_SRC" ]]; then
  RULE_SRC="$ROOT/extras/cursor-routing.mdc"
fi
RULE_DEST="${CURSOR_RULES_DIR:-$HOME/.cursor/rules}/cometweb-agent-skills.mdc"
if [[ -f "$RULE_SRC" && -L "$RULE_DEST" ]]; then
  preflight_existing_path "$RULE_DEST" "$RULE_SRC"
fi
count=0
while IFS= read -r name; do
  [[ -z "$name" ]] && continue
  src="$ROOT/skills/$name"
  dest="$TARGET/$name"
  if [[ ! -d "$src" ]]; then
    echo "FAIL: missing skill directory $src" >&2
    exit 1
  fi
  install_skill_link "$src" "$dest" "$name"
  count=$((count + 1))
done <<< "$skill_names"

if [[ -f "$RULE_SRC" ]]; then
  mkdir -p "$(dirname "$RULE_DEST")"
  if [[ -L "$RULE_DEST" ]]; then
    if [[ "$(readlink "$RULE_DEST")" == "$RULE_SRC" ]]; then
      echo "routing rule already linked -> $RULE_DEST"
    else
      backup_existing_path "$RULE_DEST" "cursor-routing.mdc"
      ln -s -- "$RULE_SRC" "$RULE_DEST"
      echo "linked routing rule -> $RULE_DEST"
    fi
  elif [[ ! -e "$RULE_DEST" ]]; then
    ln -s -- "$RULE_SRC" "$RULE_DEST"
    echo "linked routing rule -> $RULE_DEST"
  elif grep -q 'generated by tooling/generate_adapters.py' "$RULE_DEST" 2>/dev/null; then
    tmp="${RULE_DEST}.tmp.$$"
    cp -- "$RULE_SRC" "$tmp"
    mv -- "$tmp" "$RULE_DEST"
    echo "updated generated routing rule -> $RULE_DEST"
  else
    echo "skip routing rule: $RULE_DEST already exists"
  fi
fi

print_install_backup_summary
echo "OK: $count Cursor skills installed in $TARGET"
