#!/usr/bin/env python3
"""Measure what a host pays, in context, to have these skills available.

Correctness in this repository is gated ten ways. Context cost is gated none —
yet it is the resource that decides whether a skill can be used at all. A host
that loads every SKILL.md for routing pays that bill on every session before any
work happens, and nothing here has ever measured it.

Two numbers per skill:

  front_door   SKILL.md, paid whenever the skill is loadable at all.
  depth        references/, paid only when the skill actually opens one.

A healthy skill keeps the front door small and puts detail behind it. That is
what "progressive disclosure" means operationally, and this is the measurement
that turns it from a slogan into a property.

Sizes are bytes; the token estimate is bytes/4, the usual rough ratio for
English prose. It is an estimate and is labelled as one: no tokenizer is
vendored, because a number that changes with someone's installed library is
worse than an honest approximation.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / "registry" / "context-baseline.json"
BYTES_PER_TOKEN = 4


def _text_bytes(path: Path) -> int:
    return len(path.read_bytes())


def measure_skill(directory: Path) -> dict[str, Any]:
    skill_md = directory / "SKILL.md"
    front_door = _text_bytes(skill_md) if skill_md.is_file() else 0
    references = sorted(p for p in (directory / "references").glob("*.md")) if (directory / "references").is_dir() else []
    depth = sum(_text_bytes(p) for p in references)
    return {
        "id": directory.name,
        "front_door_bytes": front_door,
        "front_door_tokens_estimated": front_door // BYTES_PER_TOKEN,
        "depth_bytes": depth,
        "depth_tokens_estimated": depth // BYTES_PER_TOKEN,
        "reference_files": len(references),
        # How much of the skill is deferred rather than paid up front. A skill
        # that carries everything in SKILL.md scores 0.0 here.
        "deferred_ratio": round(depth / (front_door + depth), 4) if (front_door + depth) else 0.0,
    }


def measure(root: Path = ROOT) -> dict[str, Any]:
    skills = sorted(p for p in (root / "skills").iterdir() if p.is_dir() and (p / "SKILL.md").is_file())
    rows = [measure_skill(p) for p in skills]
    front = [r["front_door_tokens_estimated"] for r in rows]
    return {
        "schema": "cometweb.context-budget/v1",
        "unit": "bytes; token counts are estimates at %d bytes/token" % BYTES_PER_TOKEN,
        "skill_count": len(rows),
        "total_front_door_tokens_estimated": sum(front),
        "median_front_door_tokens_estimated": int(statistics.median(front)) if front else 0,
        "max_front_door_tokens_estimated": max(front) if front else 0,
        "skills": rows,
    }


def load_baseline() -> dict[str, Any] | None:
    if not BASELINE.is_file():
        return None
    return json.loads(BASELINE.read_text(encoding="utf-8"))


def compare(current: dict[str, Any], baseline: dict[str, Any], tolerance: float) -> list[str]:
    """Report unexplained growth against the recorded baseline.

    The gate is deliberately about change, not an absolute ceiling: the right
    ceiling depends on the host, and inventing one here would assert something
    this repository cannot evidence. Growth, by contrast, is always a decision
    someone made and should be able to state.
    """
    was = {r["id"]: r for r in baseline.get("skills", [])}
    problems: list[str] = []
    for row in current["skills"]:
        previous = was.get(row["id"])
        if previous is None:
            problems.append(f"{row['id']}: new skill, not in the baseline; run --update to record it")
            continue
        before = previous["front_door_bytes"]
        after = row["front_door_bytes"]
        if before and after > before * (1 + tolerance):
            grew = (after / before - 1) * 100
            problems.append(
                f"{row['id']}: front door grew {grew:.1f}% "
                f"({before} -> {after} bytes, ~{previous['front_door_tokens_estimated']} -> "
                f"~{row['front_door_tokens_estimated']} tokens). Move detail into references/ "
                f"or run --update to accept the new cost."
            )
    for missing in sorted(set(was) - {r["id"] for r in current["skills"]}):
        problems.append(f"{missing}: in the baseline but no longer on disk; run --update")
    return problems


def render_table(report: dict[str, Any]) -> str:
    lines = [
        "# Generated context budget",
        "",
        "<!-- generated by tooling/context_budget.py — do not hand-edit -->",
        "",
        "What a host pays to have each skill available. `front door` is SKILL.md, read",
        "whenever the skill is loadable. `depth` is references/, read only when the skill",
        "opens one. `deferred` is the share of the skill held behind the front door —",
        "higher is better, and 0.0 means everything is paid up front.",
        "",
        "Token counts are estimates at %d bytes/token, not a tokenizer result." % BYTES_PER_TOKEN,
        "",
        "| Skill | Front door | ~tokens | Depth | ~tokens | Refs | Deferred |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in sorted(report["skills"], key=lambda r: -r["front_door_bytes"]):
        lines.append(
            f"| `{row['id']}` | {row['front_door_bytes']:,} B | {row['front_door_tokens_estimated']:,} "
            f"| {row['depth_bytes']:,} B | {row['depth_tokens_estimated']:,} | {row['reference_files']} "
            f"| {row['deferred_ratio']:.2f} |"
        )
    lines += [
        "",
        f"**{report['skill_count']} skills.** Loading every front door costs roughly "
        f"{report['total_front_door_tokens_estimated']:,} tokens before any work begins; "
        f"the median skill costs ~{report['median_front_door_tokens_estimated']:,} and the "
        f"largest ~{report['max_front_door_tokens_estimated']:,}.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if a front door grew beyond tolerance")
    parser.add_argument("--update", action="store_true", help="record the current measurement as the baseline")
    parser.add_argument("--table", type=Path, help="write the generated markdown table to this path")
    parser.add_argument("--tolerance", type=float, default=0.10,
                        help="growth allowed before --check fails (default 0.10 = 10%%)")
    parser.add_argument("--json", action="store_true", help="print the raw measurement")
    args = parser.parse_args(argv)

    report = measure()

    if args.table:
        args.table.parent.mkdir(parents=True, exist_ok=True)
        args.table.write_text(render_table(report), encoding="utf-8")

    if args.update:
        BASELINE.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"OK: context baseline recorded for {report['skill_count']} skills "
              f"(~{report['total_front_door_tokens_estimated']:,} front-door tokens)")
        return 0

    if args.check:
        baseline = load_baseline()
        if baseline is None:
            print("FAIL: no context baseline; run tooling/context_budget.py --update", file=sys.stderr)
            return 1
        problems = compare(report, baseline, args.tolerance)
        if problems:
            for problem in problems:
                print(f"FAIL: {problem}", file=sys.stderr)
            return 1
        print(f"OK: context budget ({report['skill_count']} skills, "
              f"~{report['total_front_door_tokens_estimated']:,} front-door tokens)")
        return 0

    print(json.dumps(report, ensure_ascii=False, indent=2) if args.json else render_table(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
