#!/usr/bin/env python3
"""Generate host adapters and compatibility docs from registry sources of truth.

Writes:
  - docs/generated-skills-table.md
  - docs/generated-cursor-routing.mdc
  - docs/generated-compatibility-matrix.md
  - skills/<id>/agents/openai.yaml interface block
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry" / "skills.json"
HOSTS_FILE = ROOT / "registry" / "hosts.json"
SKILLS = ROOT / "skills"
OUT_DOCS = ROOT / "docs" / "generated-skills-table.md"
OUT_CURSOR = ROOT / "docs" / "generated-cursor-routing.mdc"
OUT_COMPAT = ROOT / "docs" / "generated-compatibility-matrix.md"

DISPLAY_NAMES = {
    "cometweb-context": "CometWeb Context",
    "evidence-researcher": "Evidence Researcher",
    "skill-orchestrator": "Skill Orchestrator",
    "skill-orchestrator-multiagent": "Skill Orchestrator Multiagent",
    "ai-council": "AI Council",
    "repo-to-roadmap": "Repo to Roadmap",
    "product-operator": "Product Operator",
    "release-readiness": "Release Readiness",
    "web-app-auditor": "Web App Auditor",
    "competitive-intelligence": "Competitive Intelligence",
    "product-teardown": "Product Teardown",
    "design-partner-finder": "Design Partner Finder",
    "customer-ops": "Customer Ops",
    "seo-geo-aeo-maxxing": "SEO GEO AEO Maxxing",
    "ai-humanize": "AI Humanize",
    "founder-led-sales-operator": "Founder-led Sales Operator",
    "research-program-operator": "Research Program Operator",
    "portfolio-operator": "Portfolio Operator",
    "longform-publisher": "Longform Publisher",
}

DEFAULT_PROMPTS = {
    "cometweb-context": (
        "Refresh the minimal CometWeb context needed for my goal and return a "
        "ContextEnvelope with sources, facts, conflicts, gaps, and handoff."
    ),
    "evidence-researcher": (
        "Build an Evidence Pack for my question: decompose claims, verify sources, "
        "run falsifier passes, and report readiness without making the final decision."
    ),
    "skill-orchestrator": (
        "Plan and execute the multi-skill workflow for my goal. Choose execution_mode "
        "auto|single_thread|isolated_subagents and hand off via CW-AIP envelopes."
    ),
    "skill-orchestrator-multiagent": (
        "Run the multi-skill workflow with execution_mode=isolated_subagents "
        "(one Task/subagent per specialist skill)."
    ),
    "ai-council": (
        "Run AI Council on my decision question. Use the smallest profile "
        "(LIGHT|STANDARD|DEEP) that protects the decision."
    ),
}


def title_case_skill(skill_id: str) -> str:
    return DISPLAY_NAMES.get(skill_id, skill_id.replace("-", " ").title())


def short_description(entry: dict) -> str:
    owns = entry.get("owns") or []
    if owns:
        text = "; ".join(owns[:3])
        return text[:140]
    return entry.get("description", "")[:140]


def render_openai_yaml(entry: dict, existing: str | None, skill_dir: Path | None = None) -> str:
    skill_id = entry["id"]
    display = title_case_skill(skill_id)
    short = short_description(entry)
    default_prompt = DEFAULT_PROMPTS.get(
        skill_id,
        f"Use the {display} skill for: {entry.get('description', skill_id)[:200]}",
    )
    allow_implicit = "false" if entry.get("explicit_only") else "true"

    products = ["chatgpt", "codex", "api", "atlas"]
    if existing:
        match = re.search(r"products:\n((?:  - .+\n)+)", existing)
        if match:
            products = [line.strip()[2:] for line in match.group(1).splitlines() if line.strip()]

    lines = [
        "interface:",
        f"  display_name: {display}",
        f"  short_description: {short}",
        f"  default_prompt: \"{default_prompt}\"",
    ]
    actual_dir = skill_dir or (SKILLS / skill_id)
    if (actual_dir / "assets" / "icon.svg").is_file():
        lines.extend([
            "  icon_small: ./assets/icon.svg",
            "  icon_large: ./assets/icon.svg",
        ])
    lines.extend([
        "policy:",
        "  products:",
    ])
    for product in products:
        lines.append(f"  - {product}")
    lines.append(f"  allow_implicit_invocation: {allow_implicit}")
    lines.append("")
    return "\n".join(lines)


def build_docs(skills: list[dict]) -> str:
    rows = [
        "# Generated skills table",
        "",
        "<!-- generated by tooling/generate_adapters.py — do not hand-edit -->",
        "",
        "| id | version | tier | lifecycle | release_status | desc_len | explicit_only |",
        "| --- | ---: | --- | --- | --- | ---: | --- |",
    ]
    for skill in skills:
        rows.append(
            f"| `{skill['id']}` | {skill['version']} | {skill.get('tier', '')} | "
            f"{skill.get('lifecycle', '')} | {skill.get('release_status', 'ACTIVE')} | "
            f"{len(skill.get('description', ''))} | {skill.get('explicit_only', False)} |"
        )
    return "\n".join(rows) + "\n"


def build_cursor(skills: list[dict]) -> str:
    lines = [
        "---",
        "description: Generated CometWeb Agent Skills routing (from registry/skills.json)",
        "globs:",
        "alwaysApply: true",
        "---",
        "",
        "<!-- generated by tooling/generate_adapters.py — do not hand-edit -->",
        "",
        "# CometWeb Agent Skills routing",
        "",
        "Load skills from the installed skills directory. Prefer **one primary skill**",
        "unless the user wants a multi-step workflow — then use `skill-orchestrator`",
        "(`execution_mode`: auto | single_thread | isolated_subagents).",
        "",
        "## Primary routing",
        "",
        "| Intent | Skill |",
        "| --- | --- |",
    ]
    for skill in skills:
        if skill.get("alias_of"):
            lines.append(f"| Alias for `{skill['alias_of']}` with isolated_subagents | `{skill['id']}` |")
            continue
        owns = ", ".join(skill.get("owns") or []) or skill["id"]
        lines.append(f"| {owns} | `{skill['id']}` |")

    lines.extend(["", "## Collision guardrails", ""])
    for skill in skills:
        if not skill.get("does_not_own"):
            continue
        denied = "; ".join(skill["does_not_own"])
        explicit = " Explicit invocation only." if skill.get("explicit_only") else ""
        lines.append(f"- **{skill['id']}** — does not own: {denied}.{explicit}")

    lines.extend(["", "## Trigger examples (from registry)", ""])
    for skill in skills:
        examples = skill.get("trigger_examples") or []
        negatives = skill.get("negative_trigger_examples") or []
        if not examples and not negatives:
            continue
        lines.append(f"### `{skill['id']}`")
        for example in examples:
            lines.append(f"- trigger: {example}")
        for example in negatives:
            lines.append(f"- do not trigger: {example}")
        lines.append("")
    return "\n".join(lines) + "\n"


def _support(entry: dict, host: dict, *, format_ok: bool) -> str:
    if not format_ok:
        return "UNSUPPORTED"
    available = set(host.get("capabilities") or [])
    required = set(entry.get("required_capabilities") or [])
    optional = set(entry.get("optional_capabilities") or [])
    if required - available:
        return "UNSUPPORTED"
    if optional - available:
        return "DEGRADED"
    return "FULL"


def _targets(entry: dict) -> set[str]:
    return set(entry.get("host_targets") or entry.get("compatible_hosts") or [])


def build_compatibility_matrix(skills: list[dict], hosts: dict) -> str:
    target_hosts = [
        "chatgpt", "openai-codex", "claude-code", "cursor",
        "qwen-code", "qoder", "lingma", "alibaba-skills-portal",
    ]
    lines = [
        "# Generated compatibility matrix",
        "",
        "<!-- generated by tooling/generate_adapters.py — do not hand-edit -->",
        "",
        "`FULL` means declared default capabilities are present at the host-profile level; "
        "`DEGRADED` means the skill loads but one or more optional capabilities require a fallback; "
        "`UNSUPPORTED` means a required capability or format contract is missing; `—` means not targeted.",
        "",
        "| Skill | " + " | ".join(target_hosts) + " |",
        "| --- | " + " | ".join(["---"] * len(target_hosts)) + " |",
    ]
    for entry in skills:
        row = [f"`{entry['id']}`"]
        targets = _targets(entry)
        skill_dir = SKILLS / entry["id"]
        desc = entry.get("description", "")
        for host_name in target_hosts:
            if host_name not in targets:
                row.append("—")
                continue
            host = hosts[host_name]
            max_len = host.get("description_max")
            format_ok = max_len is None or len(desc) <= max_len
            if host.get("agents_file") and not (skill_dir / host["agents_file"]).is_file():
                format_ok = False
            row.append(_support(entry, host, format_ok=format_ok))
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines) + "\n"


def write_openai_yamls(skills: list[dict]) -> list[Path]:
    written: list[Path] = []
    for entry in skills:
        skill_dir = SKILLS / entry["id"]
        agents = skill_dir / "agents"
        agents.mkdir(parents=True, exist_ok=True)
        path = agents / "openai.yaml"
        existing = path.read_text(encoding="utf-8") if path.is_file() else None
        content = render_openai_yaml(entry, existing, skill_dir=skill_dir)
        if existing != content:
            path.write_text(content, encoding="utf-8")
            written.append(path)
    return written


def expected_artifacts(skills: list[dict]) -> dict[Path, str]:
    hosts = json.loads(HOSTS_FILE.read_text(encoding="utf-8"))["hosts"]
    artifacts = {
        OUT_DOCS: build_docs(skills),
        OUT_CURSOR: build_cursor(skills),
        OUT_COMPAT: build_compatibility_matrix(skills, hosts),
    }
    for entry in skills:
        path = SKILLS / entry["id"] / "agents" / "openai.yaml"
        existing = path.read_text(encoding="utf-8") if path.is_file() else None
        artifacts[path] = render_openai_yaml(entry, existing, skill_dir=SKILLS / entry["id"])
    return artifacts


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if generated files would change")
    parser.add_argument("--skip-openai", action="store_true", help="do not rewrite agents/openai.yaml")
    args = parser.parse_args()
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    skills = data["skills"]

    if args.check:
        artifacts = expected_artifacts(skills)
        if args.skip_openai:
            artifacts = {path: text for path, text in artifacts.items() if path in {OUT_DOCS, OUT_CURSOR, OUT_COMPAT}}
        changed = []
        for path, expected in artifacts.items():
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                changed.append(str(path.relative_to(ROOT)))
        if changed:
            raise SystemExit("generated adapters out of date:\n- " + "\n- ".join(changed))
        print("OK: generate_adapters --check")
        return

    OUT_DOCS.parent.mkdir(parents=True, exist_ok=True)
    OUT_DOCS.write_text(build_docs(skills), encoding="utf-8")
    OUT_CURSOR.write_text(build_cursor(skills), encoding="utf-8")
    hosts = json.loads(HOSTS_FILE.read_text(encoding="utf-8"))["hosts"]
    OUT_COMPAT.write_text(build_compatibility_matrix(skills, hosts), encoding="utf-8")
    written = [] if args.skip_openai else write_openai_yamls(skills)
    msg = f"OK: wrote {OUT_DOCS.relative_to(ROOT)}, {OUT_CURSOR.relative_to(ROOT)}, {OUT_COMPAT.relative_to(ROOT)}"
    if written:
        msg += f", {len(written)} openai.yaml"
    print(msg)


if __name__ == "__main__":
    main()
